name: Black Duck Intelligent Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '5 23 * * *'
    
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest

    env:
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      PROJECT: raf-hello-java
      BRANCH: ${GITHUB_REF##*/}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
 
    - name: Black Duck Scan
      uses: synopsys-sig/detect-action@v0.3.0
      with:
#          scan-mode: INTELLIGENT
          scan-mode: RAPID
          detect-version: 7.14.0          
          github-token: ${{ secrets.GITHUB_TOKEN }}
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
#          sarif: blackduck-sarif.json  
      env:
        GITHUB_TOKEN: ${{ github.token }}
