# This is a basic workflow to help you get started with Actions

name: Code-Dx

on: [push, workflow_dispatch]

jobs:
  codedx-analyze:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Code Dx Upload
        uses: ./codedx-github-action
        with:
          server-url: ${{ secrets.CDX_SERVER_URL }}
          api-key: ${{ secrets.CDX_API_KEY }}
          project-id: ${{ secrets.CDX_PROJECT_ID }}
          source-and-binaries-glob: './src/**'
          wait-for-completion: false
